// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvimqTU8QuS3yCjIU0Cgosc_C9tAJjCI0',
    appId: '1:30972237102:android:2365342f84eaf885a4d6bf',
    messagingSenderId: '30972237102',
    projectId: 'probonodemoapp',
    storageBucket: 'probonodemoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-m5BSODS-DCeVl64fTmFyg5EBuKqFGE',
    appId: '1:30972237102:ios:bdb790af87fb4a59a4d6bf',
    messagingSenderId: '30972237102',
    projectId: 'probonodemoapp',
    storageBucket: 'probonodemoapp.appspot.com',
    iosBundleId: 'com.cart.cartCraze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-m5BSODS-DCeVl64fTmFyg5EBuKqFGE',
    appId: '1:30972237102:ios:bdb790af87fb4a59a4d6bf',
    messagingSenderId: '30972237102',
    projectId: 'probonodemoapp',
    storageBucket: 'probonodemoapp.appspot.com',
    iosBundleId: 'com.cart.cartCraze',
  );
}
